import type { ColumnDef } from "@tanstack/react-table";
import type { ILocation } from "../../../../interfaces/locations";
import type { ILocationLocationType } from "interfaces/locationLocationType";
import StyleModule from "./LocationColumns.module.css"
import Tag from "../../../../comp/primitives/tag/Tag";

const columnsLocations: ColumnDef<ILocation>[] = [
    {
        accessorKey: "id",
        header: "ID",
        meta: {
            hidden: false,
            type: "number",
            mode: "range",
            autoGenerated: true,
        },
    },
    {
        accessorKey: "name",
        header: "Nombre",
        meta: {
            hidden: false,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },
    {
        id: "locationTypes",
        header: "Tipos de ubicación",
        accessorFn: (row: ILocation) => {
            const types: ILocationLocationType[] = row.location_location_type ?? [];
            const value: string = types.map((type: ILocationLocationType) => {
                if (type.location_type?.name === "Store") {
                    return "Almacén";
                } else if (type.location_type?.name === "Production") {
                    return "Planta de producción";
                }
            }).join(", ");
            return value;
        },
        meta: {
            hidden: false,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
        cell: ({ getValue }) => {
            const value = getValue<string>();
            return <div>{value}</div>;
        },
    },
    {
        id: "dirección",
        header: "Dirección",
        accessorFn: (row: ILocation) => {
            const address: string = `${row.street}, ${row.street_number}, ${row.neighborhood}, ${row.zip_code}, ${row.city}, ${row.state}, ${row.country}`;
            return address;
        },
        meta: {
            hidden: false,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
        cell: ({ getValue }) => {
            const value = getValue<string>();
            return <div>{value}</div>;
        },
    },
    {
        accessorKey: "phone",
        header: "Teléfono",
        meta: {
            hidden: false,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
        cell: ({ getValue }) => {
            const value = getValue<string>();
            return <div>{value}</div>;
        },
    },
    {
        accessorKey: "is_active",
        header: "Estado",
        meta: {
            hidden: false,
            autoGenerated: false,
            type: "boolean",
            booleanLabels: ["Detenida", "Activo"]
        },
        cell: ({ row }) => {
            const state = row.original.is_active ? "Activo" : "Detenida";
            return (
                <div className={StyleModule.containerTag}>
                    <Tag
                        label={state}
                        className={
                            state === "Activo"
                                ? StyleModule?.tagActive
                                : StyleModule?.tagInactive
                        }
                    />
                </div>
            );
        }
    }
];

export { columnsLocations };
