import type {
  ColumnDef
} from "@tanstack/react-table";
import type {
  IPartialPurchasedOrder,
} from "../../../../interfaces/purchasedOrder";
import stylesModules from "./columns.module.css";

const columnsPurchasedOrders: ColumnDef<IPartialPurchasedOrder>[] = [
  {
    accessorKey: "id",
    header: "ID",
    meta: {
      hidden: true,
      type: "number",
      mode: "range",
      autoGenerated: true,
    },
  },
  {
    accessorKey: "order_code",
    header: "Orden ID",
    meta: {
      hidden: false,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "created_at",
    header: "Fecha de orden",
    meta: {
      hidden: false,
      type: "date",
      mode: "single",
      autoGenerated: true,
    },
  },
  {
    accessorKey: "company_name",
    header: "Cliente",
    meta: {
      hidden: false,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "delivery_date",
    header: "Entrega",
    meta: {
      hidden: false,
      type: "date",
      mode: "single",
      autoGenerated: false,
    },
  },
  {
    accessorKey: "total_price",
    header: "Price",
    meta: {
      hidden: false,
      type: "number",
      mode: "range",
      autoGenerated: false,
    },
  },
  {
    accessorKey: "status",
    header: "Estado",
    meta: {
      hidden: false,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
    cell: ({ getValue }) => {
      const status = getValue() as string;
      return (
        <span
          className={'nunito-semibold ' +
            `${stylesModules.tag} ${stylesModules[status.toLowerCase()]}`
          }>{status}
        </span>
      );
    },
  },
  {
    accessorKey: "client_id",
    header: "Client ID",
    meta: {
      hidden: true,
      type: "number",
      mode: "single",
      autoGenerated: false,
    },
  },


  // ! COLUMNAS OCULTAS ************************************************** */

  {
    accessorKey: "tax_id",
    header: "Tax ID",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "email",
    header: "Email",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "email",
    },
  },
  {
    accessorKey: "phone",
    header: "Phone",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "city",
    header: "City",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "state",
    header: "State",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "country",
    header: "Country",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "address",
    header: "Address",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "payment_terms",
    header: "Payment Terms",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "zip_code",
    header: "ZIP Code",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "tax_regimen",
    header: "Tax Regimen",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "cfdi",
    header: "CFDI",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "payment_method",
    header: "Payment Method",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "client_address_id",
    header: "Client Address ID",
    meta: {
      hidden: true,
      type: "number",
      mode: "single",
      autoGenerated: false,
    },
  },
  {
    accessorKey: "shipping_address",
    header: "Shipping Address",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "shipping_city",
    header: "Shipping City",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "shipping_state",
    header: "Shipping State",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "shipping_country",
    header: "Shipping Country",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "shipping_zip_code",
    header: "Shipping ZIP Code",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "updated_at",
    header: "Updated At",
    meta: {
      hidden: true,
      type: "date",
      mode: "single",
      autoGenerated: true,
    },
  },

  // ! ************************************************** */
];

export { columnsPurchasedOrders };
