import CriticalActionButton from "../../../../../../../comp/primitives/button/custom-button/critical-action/CriticalActionButton";
import StyleModule from "./Step2.module.css";
import TertiaryActionButtonCustom from "../../../../../../../comp/primitives/button/custom-button/tertiary-action/TertiaryActionButtonCustom";
import MainActionButtonCustom from "../../../../../../../comp/primitives/button/custom-button/main-action/MainActionButtonCustom";
import type { LocationAction, LocationState } from "../../../../context/locationTypes";
import { back_step, next_step, update_location, add_location_production_line, remove_location_production_line } from "../../../../context/locationActions";
import { ArrowLeft, Bookmark, Check, Plus, Trash2, X } from "lucide-react";
import { useCallback, type Dispatch, useState, useMemo } from "react";
import UnderlineLabelInputNumeric from "./../../../../../../../comp/primitives/input/layouts/underline-label/numeric/UnderlineLabelInputNumeric";
import SwitchMantineCustom from "./../../../../../../../comp/external/mantine/switch/custom/SwitchMantineCustom";
import { Divider } from "@mantine/core";
import type { ColumnDef } from "@tanstack/react-table";
import type { IPartialProductionLine } from "interfaces/productionLines";
import GenericTableMemo from "../../../../../../../comp/primitives/table/tableContext/GenericTable";
import type { IPartialLocationProductionLine } from "interfaces/locationsProductionLines";
import type { RowAction } from "interfaces/tableTypes";


interface IStep2Props { state: LocationState, dispatch: Dispatch<LocationAction>, onCancel: () => void }

const Step2 = ({ state, dispatch, onCancel }: IStep2Props) => {

    // ********** States **********

    const [productionCapacity, setProductionCapacity] = useState<number | null>(state.data?.production_capacity ?? null);

    const productionLines = useMemo(() => {
        return state.data.location_production_line && state.data.location_production_line.length > 0
            ? state.data.location_production_line.map((item) => (item.production_line as IPartialProductionLine)) : []
    }, [state.data.location_production_line]);

    const handleOnAddProductionLines = useCallback((newData: IPartialProductionLine[]) => {
        const newDataLocationProductionLine: IPartialLocationProductionLine[] = newData.map((item: IPartialProductionLine) => ({
            production_line_id: Number(item.id),
            production_line: item,
        }));
        dispatch(add_location_production_line(newDataLocationProductionLine));
    }, [dispatch]);

    const handleOnRemoveProductionLines = useCallback((newData: IPartialProductionLine) => {
        dispatch(remove_location_production_line([Number(newData.id)]));
    }, [dispatch]);

    // ********** Components for ProductionLine table **********

    const getRowId = useMemo(() => (row: IPartialProductionLine, index: number) => row?.id ? row.id.toString() : index.toString(), []);

    const columnsProductionLines: ColumnDef<IPartialProductionLine>[] = useMemo(() => [
        {
            accessorKey: "custom_id",
            header: "ID",
            meta: {
                hidden: false,
                autoGenerated: true,
                type: "string",
            }
        },
        {
            accessorKey: "name",
            header: "Nombre",
            meta: {
                hidden: false,
                autoGenerated: true,
                type: "string",
            }
        }
    ], []);

    const actionsRowProductionLine: RowAction<IPartialProductionLine>[] = useMemo(() => [
        {
            id: "delete",
            label: "Eliminar",
            onClick: () => { },
            icon: <Trash2 className={StyleModule.iconTrash} />
        }
    ], []);

    // ********** Components for Products asinged Table **********

    // ********** Functions **********

    const handleOnChangeActive = useCallback((value: boolean) => dispatch(update_location({ is_active: value })), []);
    const handleOnClickNext = useCallback(() => dispatch(next_step()), [dispatch]);
    const handleOnClickBack = useCallback(() => dispatch(back_step()), [dispatch]);

    return (
        <div className={StyleModule.containerStep}>
            <div className={StyleModule.containerContent}>
                <UnderlineLabelInputNumeric
                    value={productionCapacity}
                    onChange={setProductionCapacity}
                    label="Capacidad de producción"
                    withValidation
                />
                <div className={StyleModule.productionBlock}>
                    <h2 className={`nunito-bold ${StyleModule.subTitle}`}>Planta de producción</h2>
                    <div className={StyleModule.productionBlockButtonContainer}>
                        <span className={`nunito-bold ${StyleModule.subTitleSpan}`}>Líneas de producción</span>
                        <div>
                            <MainActionButtonCustom
                                label="Línea nueva"
                                onClick={() => console.log("agregar")}
                                icon={<Plus />}
                            />
                            <MainActionButtonCustom
                                label="Asignar líneas"
                                onClick={() => console.log("agregar")}
                                icon={<Plus />}
                            />
                        </div>
                    </div>
                    <GenericTableMemo
                        // modelo e indentificador
                        modelName="Líneas de producción"
                        getRowId={getRowId}

                        // data y columnas
                        columns={columnsProductionLines}
                        data={productionLines}

                        // funcionalidades 
                        enablePagination
                        enableOptionsColumn
                        typeRowActions="icon"
                        rowActions={actionsRowProductionLine}
                    />
                </div>
                <div className={StyleModule.inventoryBlock}>
                    <h2 className={`nunito-bold ${StyleModule.subTitle}`}>Almacén</h2>
                </div>
                <div className={StyleModule.containerSwitch}>
                    <span className={`nunito-bold ${StyleModule.subTitleSpan}`}>Activar ubicación</span>
                    <SwitchMantineCustom
                        value={state.data?.is_active ?? true}
                        onChange={handleOnChangeActive}
                        size="lg"
                        labelOff="Inactiva"
                        labelOn="Activa"
                        iconActive={<Check />}
                        iconInactive={<X />}
                        color="var(--color-theme-primary)"
                    />
                </div>
                <Divider color="var(--color-theme-primary-light)" />
            </div>
            <div className={StyleModule.containerButtons}>
                <CriticalActionButton
                    label="Cancelar"
                    onClick={onCancel}
                />
                <TertiaryActionButtonCustom
                    label="Regresar"
                    onClick={handleOnClickBack}
                    icon={<ArrowLeft />}
                />
                <TertiaryActionButtonCustom
                    label="Guardar y salir"
                    onClick={() => console.log("guardar y salir")}
                    icon={<Bookmark />}
                />
                <MainActionButtonCustom
                    label="Guardar y continuar"
                    onClick={handleOnClickNext}
                    icon={<Bookmark />}
                />
            </div>
        </div>
    );
}

export default Step2;
