import type {
    ColumnDef
} from "@tanstack/react-table";
import type {
    ILocation
} from "../../../../../interfaces/locations";

const columnsLocations: ColumnDef<ILocation>[] = [
    {
        accessorKey: "id",
        header: "ID",
        meta: {
            hidden: true,
            type: "number",
            mode: "range",
            autoGenerated: true,
        },
    },
    {
        accessorKey: "name",
        header: "Name",
        meta: {
            hidden: false,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "description",
        header: "Description",
        meta: {
            hidden: false,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "is_active",
        header: "Is Active",
        meta: {
            hidden: false,
            type: "boolean",
            autoGenerated: false,
            booleanLabels: [ "Inactive", "Active" ],
        },
    },
    {
        accessorKey: "created_at",
        header: "Created At",
        meta: {
            hidden: true,
            type: "date",
            mode: "range",
            autoGenerated: true,
        },
    },
    {
        accessorKey: "updated_at",
        header: "Updated At",
        meta: {
            hidden: true,
            type: "date",
            mode: "range",
            autoGenerated: true,
        },
    },
];

export { columnsLocations };
