import type { ColumnDef } from "@tanstack/react-table"
import { getEnumoSingleLabel } from "../../../../comp/primitives/table/tableContext/tableTypes";
import type { IInput } from "../../../../interfaces/inputs";
import type { IItem } from "../../../../interfaces/item";
import type { IProduct } from "../../../../interfaces/product";
import { formatCurrency } from "./../../../../helpers/formttersNumeric"

const ItemsColumns: ColumnDef<IItem>[] = [
    {
        id: "custom_id",
        accessorFn: (row: IItem) => row.item?.custom_id?.toString(),
        header: "ID",
        meta: {
            hidden: false,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },

    {
        id: "name",
        accessorFn: (row: IItem) => row.item?.name,
        header: "Producto",
        meta: {
            hidden: false,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },
    {
        id: "description",
        accessorFn: (row: IItem) => row.item?.description,
        header: "Descripcion",
        meta: {
            hidden: false,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "item_type",
        header: "Categoría",
        meta: {
            hidden: false,
            type: "enum",
            enumOptions: [
                { label: "Producto terminado", value: "product" },
                { label: "Materia prima", value: "input" },
            ],
            autoGenerated: false,
        },
        cell: ({ getValue, column}) => {
            const value = getValue() as string;
            const labelEnum = getEnumoSingleLabel(column.columnDef, value) || "";
            return (
                <div>
                    {labelEnum}
                </div>
            );
        }
    },
    {
        id: "precio",
        accessorFn: (row: IItem) => {
            if (!row.item) return null;

            let price: number = 0;

            if (row.item_type === "input") {
                // autocomplete completo de IInput
                const input = row.item as IInput;
                price = Number(input?.unit_cost);
            } else {
                // autocomplete completo de IProduct
                const product = row.item as IProduct;
                price = Number(product.sale_price);
            }
            return price;
        },
        header: "Precio de venta / Precio de compra",
        cell: ({ getValue }) => {
            const value = getValue() as number;
            return formatCurrency(value);
        },
        meta: {
            hidden: false,
            type: "number",
            mode: "range",
            autoGenerated: false,
        },
    },


]

export default ItemsColumns;