import type { ColumnDef } from "@tanstack/react-table"
import type { IItem } from "interfaces/item";

const ItemsColumns: ColumnDef<IItem>[] = [
    {
        accessorKey: "id",
        header: "ID",
        meta: {
            hidden: false,
            type: "number",
            mode: "range",
            autoGenerated: true,
        },
    },
    {
        accessorKey: "item_id",
        header: "ID item",
        meta: {
            hidden: false,
            type: "number",
            mode: "range",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "item_type",
        header: "Tipo",
        meta: {
            hidden: false,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    }
]

export default ItemsColumns;