import type {
    ColumnDef
} from "@tanstack/react-table";
import type {
    IInternalProductProductionOrder
} from "../../../../../interfaces/internalOrder";

const columnsInternalProductProductionOrders:
    ColumnDef<IInternalProductProductionOrder>[] = [
        {
            accessorKey: "id",
            header: "ID",
            meta: {
                hidden: false,
                type: "number",
                mode: "range",
                autoGenerated: true,
            },
        },
        {
            accessorKey: "product_id",
            header: "Product ID",
            meta: {
                hidden: true,
                type: "number",
                mode: "single",
                autoGenerated: false,
            },
        },
        {
            accessorKey: "product_name",
            header: "Product Name",
            meta: {
                hidden: false,
                type: "string",
                typeText: "text",
                autoGenerated: false,
            },
        },
        {
            accessorKey: "qty",
            header: "Quantity",
            meta: {
                hidden: false,
                type: "number",
                mode: "range",
                autoGenerated: false,
            },
        },
        {
            accessorKey: "status",
            header: "Status",
            meta: {
                hidden: false,
                type: "string",
                typeText: "text",
                autoGenerated: false,
            },
        },
        {
            accessorKey: "location_id",
            header: "Location ID",
            meta: {
                hidden: true,
                type: "number",
                mode: "single",
                autoGenerated: false,
            },
        },
        {
            accessorKey: "location_name",
            header: "Location Name",
            meta: {
                hidden: false,
                type: "string",
                typeText: "text",
                autoGenerated: false,
            },
        },
        {
            accessorKey: "created_at",
            header: "Created At",
            meta: {
                hidden: false,
                type: "date",
                mode: "single",
                autoGenerated: true,
            },
        },
        {
            accessorKey: "updated_at",
            header: "Updated At",
            meta: {
                hidden: true,
                type: "date",
                mode: "single",
                autoGenerated: true,
            },
        },
    ];


export { columnsInternalProductProductionOrders }