import type {
    ColumnDef
} from "@tanstack/react-table";
import type {
    ILocationType
} from "../../../interfaces/locationTypes";

const columnsLocationTypes:
    ColumnDef<ILocationType>[] = [
        {
            accessorKey: 'id',
            header: 'Id',
            meta: {
                type: 'number',
                mode: "range",
                autoGenerated: true,
                hidden: true,
            },
        },
        {
            accessorKey: 'name',
            header: 'Name',
            meta: {
                type: 'string',
                autoGenerated: false,
                typeText: "text",
            },
            enableHiding: false,
        },
        {
            accessorKey: 'created_at',
            header: 'Created At',
            meta: {
                autoGenerated: true,
                type: "date",
                mode: "single"
            }
        },
        {
            accessorKey: 'updated_at',
            header: 'Updated At',
            meta: {
                autoGenerated: true,
                type: "date",
                mode: "single"
            }
        }
    ]

export { columnsLocationTypes };


