import type { ColumnDef }
    from "@tanstack/react-table";
import type { IShippingOrder }
    from "../../../interfaces/shippingOrder";

const columnsShippingOrders: ColumnDef<IShippingOrder>[] = [
    {
        accessorKey: "id",
        header: "ID",
        meta: {
            hidden: true,
            type: "number",
            mode: "range",
            autoGenerated: true,
        },
    },
    {
        accessorKey: "code",
        header: "Code",
        meta: {
            hidden: false,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "status",
        header: "Status",
        meta: {
            hidden: false,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "carrier_id",
        header: "Carrier ID",
        meta: {
            hidden: false,
            type: "number",
            mode: "single",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "load_evidence",
        header: "Load Evidence",
        meta: {
            hidden: true,
            type: "string",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "delivery_cost",
        header: "Delivery Cost",
        meta: {
            hidden: false,
            type: "number",
            mode: "range",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "created_at",
        header: "Created At",
        meta: {
            hidden: true,
            type: "date",
            mode: "single",
            autoGenerated: true,
        },
    },
    {
        accessorKey: "updated_at",
        header: "Updated At",
        meta: {
            hidden: true,
            type: "date",
            mode: "single",
            autoGenerated: true,
        },
    },
];

export { columnsShippingOrders };
