import TertiaryActionButtonCustom from "../../../../../../../comp/primitives/button/custom-button/tertiary-action/TertiaryActionButtonCustom";
import MainActionButtonCustom from "../../../../../../../comp/primitives/button/custom-button/main-action/MainActionButtonCustom";
import type { IPartialLocationProductionLine } from "../../../../../../../interfaces/locationsProductionLines";
import type { IPartialInventoryLocationItem } from "../../../../../../../interfaces/inventoriesLocationsItems";
import GenericTableMemo from "../../../../../../../comp/primitives/table/tableContext/GenericTable";
import type { IPartialProductionLineProduct } from "interfaces/productionLinesProducts";
import type { LocationAction, LocationState } from "../../../../context/locationTypes";
import { ArrowLeft, Pencil } from "lucide-react";
import Tag from "../../../../../../../comp/primitives/tag/Tag";
import { useCallback, type Dispatch, useMemo } from "react";
import { set_step, set_draft_location } from "../../../../context/locationActions";
import type { ColumnDef } from "@tanstack/react-table";
import { Divider } from "@mantine/core";
import StyleModule from "./Step3.module.css";

interface IStep3Props {
    state: LocationState,
    dispatch: Dispatch<LocationAction>,
    onClose: () => void
}

const Step3 = ({ state, dispatch, onClose }: IStep3Props) => {

    // ********** Components for ProductionLine table **********

    const getRowIdLocationProductionLine = useMemo(() => (row: IPartialLocationProductionLine, index: number) => row?.id ? row.id.toString() : index.toString(), []);

    const columnsLocationProductionLine: ColumnDef<IPartialLocationProductionLine>[] = useMemo(() => [
        {
            id: "customId",
            accessorFn: (row) => row.production_line?.custom_id,
            header: "ID",
            meta: {
                hidden: false,
                autoGenerated: true,
                type: "string",
            },
            cell: ({ row }) => (<div>{row.original.production_line?.custom_id}</div>)
        },
        {
            id: "name",
            accessorFn: (row) => row.production_line?.name,
            header: "Nombre",
            meta: {
                hidden: false,
                autoGenerated: true,
                type: "string",
            },
            cell: ({ row }) => (<div>{row.original.production_line?.name}</div>)

        },
        {
            id: "products",
            accessorFn: (row) => row.production_line?.name,
            header: "Productos asignados",
            meta: {
                hidden: false,
                autoGenerated: true,
                type: "array",
            },
            cell: ({ row }) => {
                const values: IPartialProductionLineProduct[] = row.original.production_line?.production_lines_products ?? [];
                return (
                    <div className={StyleModule.containerProductionLineProducts}>
                        {values?.map((plp, index) => {
                            return <div key={index}>{plp.products?.name}</div>
                        })}
                    </div>
                );
            }
        }
    ], []);


    // ********** Components for Products asinged Table **********

    // ********** Functions **********

    const getRowIdInventoryLocationItem = useMemo(() => (row: IPartialInventoryLocationItem, index: number) => row?.id ? row.id.toString() : index.toString(), []);

    const handleOnClickBack = useCallback(() => onClose(), [onClose]);
    const handleOnClickEdit = useCallback(async () => {
        dispatch(set_draft_location(state.data));
        dispatch(set_step(0));
    }, [dispatch, state.data]);

    const columns: ColumnDef<IPartialInventoryLocationItem>[] = useMemo(() => [
        {
            accessorFn: (row) => row.item?.item?.id,
            header: "ID",
            meta: {
                hidden: false,
                autoGenerated: true,
                type: "string",
            }
        },
        {
            accessorFn: (row) => row.item?.item?.name,
            header: "Producto",
            meta: {
                hidden: false,
                autoGenerated: true,
                type: "string",
            }
        },
        {
            accessorFn: (row) => row.item?.item?.description,
            header: "Descripción",
            meta: {
                hidden: false,
                autoGenerated: true,
                type: "string",
            }
        }
    ], []);

    return (
        <div className={StyleModule.containerStep}>
            <div className={StyleModule.containerContent}>
                <div className={StyleModule.informationBlock}>
                    <h2 className={`nunito-bold ${StyleModule.subTitle}`}>Información de ubicación</h2>
                    <div className={StyleModule.rowBlock}>
                        <div className={`nunito-bold ${StyleModule.firstBlock}`}>
                            <dl className={StyleModule.definitionList}>
                                <dt>{`Nombre de la ubicación: `}</dt>
                                <dd>{state.data.name}</dd>
                            </dl>
                            <dl className={StyleModule.definitionList}>
                                <dt>{`ID único: `}</dt>
                                <dd>{state.data.custom_id}</dd>
                            </dl>
                            <dl className={StyleModule.definitionList}>
                                <dt>{`Dirección: `}</dt>
                                <dd>{`${state.data.street} ${state.data.street_number}, ${state.data.neighborhood}, ${state.data.city}, ${state.data.state}, ${state.data.country}`}</dd>
                            </dl>
                        </div>
                        <div className={`nunito-bold ${StyleModule.firstBlock}`}>
                            <dl className={StyleModule.definitionList}>
                                <dt>{`Teléfono: `}</dt>
                                <dd>{state.data.phone}</dd>
                            </dl>
                            <dl className={StyleModule.definitionList}>
                                <dt>{`Responsable: `}</dt>
                                <dd>{state.data.location_manager}</dd>
                            </dl>
                            <dl className={StyleModule.definitionList}>
                                <dt>{`Tipo de ubicación: `}</dt>
                                <dd>
                                    {state.data.location_location_type?.map(
                                        llt => (llt.location_type?.name as string) === "Store"
                                            ? "Almacén" : "Planta de producción"
                                    ).join(",")}
                                </dd>
                            </dl>
                        </div>
                    </div>
                </div>
                <div className={StyleModule.productionBlock}>
                    <h2 className={`nunito-bold ${StyleModule.subTitle}`}>Planta de producción</h2>
                    <div className={`nunito-bold ${StyleModule.firstBlock}`}>
                        <dl className={StyleModule.definitionList}>
                            <dt>{`Capacidad de producción: `}</dt>
                            <dd>{`${state.data.production_capacity} unidades`}</dd>
                        </dl>
                    </div>
                    <GenericTableMemo
                        // modelo e indentificador
                        modelName="Locations production lines"
                        getRowId={getRowIdLocationProductionLine}
                        // data y columnas
                        columns={columnsLocationProductionLine}
                        data={state.data?.location_production_line ?? []}
                    />
                </div>
                <div className={StyleModule.inventoryBlock}>
                    <h2 className={`nunito-bold ${StyleModule.subTitle}`}>Almacén</h2>
                    <div className={StyleModule.inventoryBlockButtonContainer}>
                    </div>
                    <GenericTableMemo
                        modelName="products asignados a almacen"
                        getRowId={getRowIdInventoryLocationItem}
                        noResultsMessage="No hay productos asignados"
                        columns={columns}
                        data={state.data?.inventories_locations_items || []}
                    />
                </div>
                <div className={StyleModule.statusBlock}>
                    <dl className={StyleModule.dlStatus}>
                        <dt className={`nunito-bold`}>Estado de la línea:</dt>
                        <dd>
                            <Tag
                                label={state.data?.is_active ? "Activa" : "Inactiva"}
                                className={state.data?.is_active ? StyleModule.tagActive : StyleModule.tagInactive}
                            />
                        </dd>
                    </dl>
                </div>
                <Divider color="var(--color-theme-primary-light)" />
            </div>
            <div className={StyleModule.containerButtons}>
                <TertiaryActionButtonCustom
                    label="Regresar"
                    onClick={handleOnClickBack}
                    icon={<ArrowLeft />}
                />
                <MainActionButtonCustom
                    label="Editar"
                    onClick={handleOnClickEdit}
                    icon={<Pencil />}
                />
            </div>
        </div>
    );
}

export default Step3;
