import TertiaryActionButtonCustom from "../../../../../../../comp/primitives/button/custom-button/tertiary-action/TertiaryActionButtonCustom";
import MainActionButtonCustom from "../../../../../../../comp/primitives/button/custom-button/main-action/MainActionButtonCustom";
import CriticalActionButton from "../../../../../../../comp/primitives/button/custom-button/critical-action/CriticalActionButton";
import SingleImageLoaderCustom from "../../../../../../../comp/primitives/image-loader/single/custom/SingleImageLoaderCustom";
import type { IPartialProductDiscountRange } from "../../../../../../../interfaces/product-discounts-ranges";
import GenericTableMemo from "../../../../../../../comp/primitives/table/tableContext/GenericTable";
import type { IPartialProductProcess } from "../../../../../../../interfaces/productsProcesses";
import { formatCurrency, formatNumber } from "../../../../../../../helpers/formttersNumeric"
import type { IPartialProductInput } from "../../../../../../../interfaces/productsInputs";
import base64ToFileOrNull from "../../.../../../../../../../scripts/convertBase64ToFile";
import type { IPartialProduct } from "../../../../../../../interfaces/product";
import type { ItemAction, ItemState } from "../../../../../context/itemTypes";
import type { IPartialInput } from "../../../../../../../interfaces/inputs";
import { useCallback, useMemo, useState, type Dispatch } from "react";
import { back_step } from "../../../../../context/itemActions";
import type { ColumnDef } from "@tanstack/react-table";
import StyleModule from "./Step3.module.css"
import { Bookmark } from "lucide-react";

interface Step3Props {
    state: ItemState,
    dispatch: Dispatch<ItemAction>,
    onCancel: () => void
}

const Step3 = ({ state, dispatch, onCancel }: Step3Props) => {

    const computePhotoFiles = useCallback((): File | null => {
        if (!state.data.item) return null;
        return base64ToFileOrNull(state.data.item?.photo || null, "photo")
    }, [state.data.item]);

    const [photo, setPhoto] = useState<File | null>(computePhotoFiles());


    //  * ************ Components Table ProductInput ************ 

    const getRowIdProductInput = useMemo(() => (row: IPartialProductInput, index: number) => row.inputs?.id && row.inputs.id?.toString() || index.toString(), []);

    const columnsProductInput: ColumnDef<IPartialProductInput>[] = useMemo(() => [
        {
            id: "custom_id",
            header: "Id",
            accessorFn: (row: IPartialProductInput) => row.inputs?.custom_id,
            meta: {
                hidden: false,
                type: "number",
                mode: "range",
                autoGenerated: false,
            },
        },
        {
            id: "name",
            header: "Insumo",
            accessorFn: (row: IPartialProductInput) => row.inputs?.name,
            meta: {
                hidden: false,
                type: "string",
                typeText: "text",
                autoGenerated: false,
            },
        },
    ], []);

    //  * ************ Components Table ProductProcess ************ 

    const getRowIdProductProcess = useMemo(() => (row: IPartialProductProcess, index: number) => (row?.process_id && row?.process_id.toString()) || index.toString(), []);

    const columnsProductProcess: ColumnDef<IPartialProductProcess>[] = useMemo(() => [
        {
            id: "name",
            header: "Nombre",
            accessorFn: (row: IPartialProductProcess) => row.process?.name,
            meta: {
                hidden: false,
                type: "string",
                typeText: "text",
                autoGenerated: false,
            },
        },
        {
            id: "sort_order",
            header: "Orden",
            accessorFn: (row: IPartialProductProcess) => row.sort_order,
            meta: {
                hidden: false,
                type: "number",
                mode: "range",
                autoGenerated: false,
            },
        },
    ], []);

    //  * ************ Components Table ProductDiscountRange ************ 

    const getRowIdProductDiscountRange = useMemo(() => (row: IPartialProductDiscountRange, index: number) => (row?.id && row?.id.toString()) || index.toString(), []);


    const columnsProductDiscountRange: ColumnDef<IPartialProductDiscountRange>[] = useMemo(() => [
        {
            accessorKey: "min_qty",
            header: "Mínimo de piezas",
            meta: {
                hidden: false,
                type: "number",
                mode: "range",
                autoGenerated: false,
            },
            cell: ({ row }) => formatNumber(Number(row.original.min_qty))
        },
        {
            accessorKey: "max_qty",
            header: "Máximo de piezas",
            meta: {
                hidden: false,
                type: "number",
                mode: "range",
                autoGenerated: false,
            },
            cell: ({ row }) => formatNumber(Number(row.original.max_qty))
        },
        {
            accessorKey: "unit_price",
            header: "Precio",
            meta: {
                hidden: false,
                type: "number",
                mode: "range",
                autoGenerated: false,
            },
            cell: ({ row }) => formatCurrency(Number(row.original.unit_price))
        },
    ], []);

    // * ************ Handlers ************ 

    const handleOnClickNextStep = useCallback(() => {

    }, [state.data.item, dispatch, photo]);

    const handleOnClickBackStep = useCallback(() => {
        dispatch(back_step());
    }, [dispatch]);

    return (
        <div className={StyleModule.containerStep}>
            <div className={StyleModule.containerContent}>
                <div className={StyleModule.firstBlock}>
                    <div className={StyleModule.imageContainer}>
                        <SingleImageLoaderCustom
                            value={photo}
                            onChange={setPhoto}
                        />
                    </div>
                    <div className={StyleModule.infoContainer}>
                        <div>
                            <h2 className="nunito-bold">Información del producto</h2>
                            <dl>
                                <dt>Nombre del producto</dt>
                                <dd>{state.data.item?.name}</dd>
                            </dl>
                            <dl>
                                <dt>ID único</dt>
                                <dd>{state.data.item?.custom_id}</dd>
                            </dl>
                            <dl>
                                <dt>Categoría</dt>
                                <dd>
                                    {
                                        state.data.item_type === "product"
                                            ? "Producto terminado"
                                            : "Materia prima"
                                    }
                                </dd>
                            </dl>
                            <dl>
                                <dt>Código de barras</dt>
                                <dd>{state.data.item?.barcode}</dd>
                            </dl>
                            <dl>
                                <dt>Descripción del producto</dt>
                                <dd>{state.data.item?.description}</dd>
                            </dl>
                        </div>
                        <div>
                            <h2 className="nunito-bold">Características e información adicional</h2>
                            {state.data.item?.presentation &&
                                <dl>
                                    <dt>Presentación</dt>
                                    <dd>{state.data.item?.presentation}</dd>
                                </dl>
                            }
                            {state.data.item?.storage_conditions &&
                                <dl>
                                    <dt>Condiciones de almacenamiento</dt>
                                    <dd>{state.data.item.storage_conditions}</dd>
                                </dl>
                            }
                            {state.data.item_type === "product" &&
                                <dl>
                                    <dt>Costo de producción</dt>
                                    <dd></dd>
                                </dl>
                            }
                            <dl>
                                <dt>
                                    {
                                        state.data.item_type === "product"
                                            ? "Precio de venta"
                                            : "Precio de compra"
                                    }
                                </dt>
                                <dd>
                                    {
                                        state.data.item_type === "product"
                                            ? (state.data.item as IPartialProduct).sale_price
                                            : (state.data.item as IPartialInput).unit_cost
                                    }
                                </dd>
                            </dl>
                        </div>
                    </div>
                </div>
                {state.data.item_type === "product" &&
                    <div className={StyleModule.externalContainerTable}>
                        <div className={StyleModule.contentHeaderTable}>
                            <span className={`nunito-bold ${StyleModule.subTitle}`}>Insumos de producción</span>
                        </div>
                        <GenericTableMemo
                            modelName="Insumos de producción"
                            getRowId={getRowIdProductInput}
                            data={(state.data.item as IPartialProduct).products_inputs || []}
                            columns={columnsProductInput}
                            modeTable="content"
                            noResultsMessage="No hay insumos de producción asignados"
                        />
                    </div>
                }
                {state.data.item_type === "product" &&
                    <div className={StyleModule.externalContainerTable}>
                        <div className={StyleModule.contentHeaderTable}>
                            <span className={`nunito-bold ${StyleModule.subTitle}`}>Procesos de producción</span>
                        </div>
                        <GenericTableMemo
                            modelName="Procesos de producción"
                            getRowId={getRowIdProductProcess}
                            data={(state.data.item as IPartialProduct).product_processes || []}
                            columns={columnsProductProcess}
                            modeTable="content"
                            noResultsMessage="No hay procesos de producción asignados"
                        />
                    </div>
                }
                {state.data.item_type === "product" &&
                    <div className={StyleModule.externalContainerTable}>
                        <div className={StyleModule.contentHeaderTable}>
                            <span className={`nunito-bold ${StyleModule.subTitle}`}>Descuentos de rangos</span>
                        </div>
                        <GenericTableMemo
                            modelName="Descuentos de rangos"
                            getRowId={getRowIdProductDiscountRange}
                            data={(state.data.item as IPartialProduct).product_discount_ranges || []}
                            columns={columnsProductDiscountRange}
                            modeTable="content"
                            noResultsMessage="No hay descuentos de rangos asignados"
                        />
                    </div>
                }
            </div>
            <div className={StyleModule.containerButtons}>
                <CriticalActionButton
                    label="Cancelar"
                    onClick={onCancel}
                />
                <CriticalActionButton
                    label="Regresar"
                    onClick={handleOnClickBackStep}
                />
                <TertiaryActionButtonCustom
                    label="Guardar y salir"
                    onClick={() => console.log("guardar y salir")}
                    icon={<Bookmark />}
                />
                <MainActionButtonCustom
                    label="Guardar y continuar"
                    onClick={handleOnClickNextStep}
                    icon={<Bookmark />}
                />
            </div>
        </div >
    )
}

export default Step3;