import UnderlineLabelInputNumeric from "../../../../../../../comp/primitives/input/layouts/underline-label/numeric/UnderlineLabelInputNumeric";
import UnderlineLabelInputText from "../../../../../../../comp/primitives/input/layouts/underline-label/text/UnderlineLabelInputText";
import TertiaryActionButtonCustom from "../../../../../../../comp/primitives/button/custom-button/tertiary-action/TertiaryActionButtonCustom";
import SingleImageLoaderCustom from "../../../../../../../comp/primitives/image-loader/single/custom/SingleImageLoaderCustom";
import MainActionButtonCustom from "../../../../../../../comp/primitives/button/custom-button/main-action/MainActionButtonCustom";
import CriticalActionButton from "../../../../../../../comp/primitives/button/custom-button/critical-action/CriticalActionButton";
import type { IPartialProductDiscountRange } from "../../../../../../../interfaces/product-discounts-ranges";
import type { IPartialProductInputProcess } from "../../../../../../../interfaces/productInpustProcesses";
import GenericTableMemo from "../../../../../../../comp/primitives/table/tableContext/GenericTable";
import type { ItemAction, ItemState } from "../../../../../context/itemTypes";
import { update_discount_from_products } from "../../../../../context/itemActions";
import { useCallback, useMemo, useState, type Dispatch } from "react";
import { back_step } from "../../../../../context/itemActions";
import type { IPartialProduct } from "interfaces/product";
import type { IPartialInput } from "interfaces/inputs";
import type { ColumnDef } from "@tanstack/react-table";
import StyleModule from "./Step2.module.css"
import { Bookmark } from "lucide-react";

interface Step2Props {
    state: ItemState,
    dispatch: Dispatch<ItemAction>,
    onCancel: () => void
}

const Step2 = ({ state, dispatch, onCancel }: Step2Props) => {

    const computeCostValue = useCallback((): number | null => {
        let value: number | null;
        if (state.data.item_type === "product") {
            const itemState = state.data.item as IPartialProduct;
            value = itemState.sale_price ?? null;
        } else {
            const itemState = state.data.item as IPartialInput;
            value = itemState.unit_cost ?? null
        }
        return value;
    }, [state.data]);

    const computeProductionCost = useCallback((): number | null => {
        let value: number | null;
        if (state.data.item_type === "product") {
            const itemState = state.data.item as IPartialProduct;
            value = itemState.production_cost ?? null;
        } else {
            value = null;
        }
        return value;
    }, [state.data]);

    const [photo, setPhoto] = useState<File | null>(null);
    const [cost, setCost] = useState<number | null>(computeCostValue());
    const [presentation, setPresentation] = useState<string | null>(state.data.item?.presentation ?? null);
    const [storageConditions, setStorageConditions] = useState<string | null>(state.data.item?.storage_conditions ?? null);
    const [productionCost, setProductionCost] = useState<number | null>(computeProductionCost());


    //  * ************ Components Table ProductInputProcess ************ 

    const getRowIdProductInputProcess = useMemo(() => (row: IPartialProductInputProcess, index: number) => (row?.id && row?.id.toString()) || index.toString(), []);

    const handleUpdateItemOrder = useCallback((items: IPartialProductInputProcess[]) => {
    }, []);

    const columnsProductInputProcess: ColumnDef<IPartialProductInputProcess>[] = useMemo(() => [
        {
            id: "name",
            header: "Nombre",
            accessorFn: (row: IPartialProductInputProcess) => row.product_process?.process?.name,
            meta: {
                hidden: false,
                type: "string",
                typeText: "text",
                autoGenerated: false,
            },
        },
        {
            id: "sort_order",
            header: "Orden",
            accessorFn: (row: IPartialProductInputProcess) => row.product_process?.sort_order,
            meta: {
                hidden: false,
                type: "number",
                mode: "range",
                autoGenerated: false,
            },
        },
    ], []);

    const getSortFieldProductInputProcess = useCallback((row: IPartialProductInputProcess): number => {
        return row.product_process?.sort_order as number;
    }, []);

    const setSortFieldProductInputProcess = useCallback((row: IPartialProductInputProcess, value: number): IPartialProductInputProcess => {
        return {
            ...row,
            product_process: {
                ...row.product_process,
                sort_order: value,
            } as IPartialProductInputProcess,
        };
    }, []);

    //  * ************ Components Table ProductDiscountRange ************ 

    const getRowIdProductDiscountRange = useMemo(() => (row: IPartialProductDiscountRange, index: number) => (row?.id && row?.id.toString()) || index.toString(), []);


    const onHandleChangeValueMinQty = useCallback((id: number, value: number | null) => {
        const attributes: IPartialProductDiscountRange = { min_qty: value as number };
        dispatch(update_discount_from_products({ id, attributes: attributes }));
    }, [dispatch]);
    const onHandleChangeValueMaxQty = useCallback((id: number, value: number | null) => {
        const attributes: IPartialProductDiscountRange = { max_qty: value as number };
        dispatch(update_discount_from_products({ id, attributes: attributes }));
    }, [dispatch]);
    const onHandleChangeValueUnitPrice = useCallback((id: number, value: number | null) => {
        const attributes: IPartialProductDiscountRange = { unit_price: value as number };
        dispatch(update_discount_from_products({ id, attributes: attributes }));
    }, [dispatch]);

    const columnsProductDiscountRange: ColumnDef<IPartialProductDiscountRange>[] = useMemo(() => [
        {
            accessorKey: "min_qty",
            header: "Mínimo de piezas",
            meta: {
                hidden: false,
                type: "number",
                mode: "range",
                autoGenerated: false,
            },
            cell: ({ row }) => {
                const value = row.original.min_qty ?? null;

                const onChange = useCallback((value: number | null) => {
                    onHandleChangeValueMinQty(row.original.id as number, value);
                }, [row.original.id, onHandleChangeValueMinQty]);

                return (
                    <UnderlineLabelInputNumeric
                        value={value}
                        onChange={onChange}
                    />
                )
            }
        },
        {
            accessorKey: "max_qty",
            header: "Máximo de piezas",
            meta: {
                hidden: false,
                type: "number",
                mode: "range",
                autoGenerated: false,
            },
            cell: ({ row }) => {
                const value = row.original.max_qty ?? null;

                const onChange = useCallback((value: number | null) => {
                    onHandleChangeValueMaxQty(row.original.id as number, value);
                }, [row.original.id, onHandleChangeValueMaxQty]);

                return (
                    <UnderlineLabelInputNumeric
                        value={value}
                        onChange={onChange}
                    />
                )
            }
        },
        {
            accessorKey: "unit_price",
            header: "Precio",
            meta: {
                hidden: false,
                type: "number",
                mode: "range",
                autoGenerated: false,
            },
            cell: ({ row }) => {
                const value = row.original.unit_price ?? null;

                const onChange = useCallback((value: number | null) => {
                    onHandleChangeValueUnitPrice(row.original.id as number, value);
                }, [row.original.id, onHandleChangeValueUnitPrice]);

                return (
                    <UnderlineLabelInputNumeric
                        value={value}
                        onChange={onChange}
                    />
                )
            }
        },
    ], [state.data, dispatch, onHandleChangeValueMinQty, onHandleChangeValueMaxQty, onHandleChangeValueUnitPrice]);


    // * ************ Handlers ************ 

    const handleOnClickNextStep = useCallback(() => {

    }, [dispatch]);

    const handleOnClickBackStep = useCallback(() => {
        dispatch(back_step());
    }, [dispatch]);

    return (
        <div className={StyleModule.containerStep}>
            <div className={StyleModule.containerContent}>
                <div className={StyleModule.firstBlock}>
                    <div className={StyleModule.imageContainer}>
                        <SingleImageLoaderCustom
                            value={photo}
                            onChange={setPhoto}
                        />
                    </div>
                    <div className={StyleModule.infoContainer}>
                        <div className={StyleModule.inputGroup}>
                            <UnderlineLabelInputText
                                label="Presentación"
                                value={presentation}
                                onChange={setPresentation}
                            />
                            <UnderlineLabelInputText
                                label="Condiciones de almacenamiento"
                                value={storageConditions}
                                onChange={setStorageConditions}
                            />
                        </div>
                        <div className={StyleModule.inputGroup}>

                            <UnderlineLabelInputNumeric
                                label={
                                    state.data.item_type === "product"
                                        ? "Precio de venta"
                                        : "Precio de compra"
                                }
                                value={cost}
                                onChange={setCost}
                                withValidation
                            />
                            {state.data.item_type === "product" &&
                                <UnderlineLabelInputNumeric
                                    label="Costo de producción"
                                    value={productionCost}
                                    onChange={setProductionCost}
                                    withValidation
                                />
                            }
                        </div>
                    </div>

                </div>
                {state.data.item_type === "product" &&
                    <div>
                        <span className={`nunito-bold ${StyleModule.subTitle}`}>Procesos de producción</span>
                        <GenericTableMemo
                            modelName="Procesos de producción"
                            getRowId={getRowIdProductInputProcess}
                            getSortField={getSortFieldProductInputProcess}
                            setSortField={setSortFieldProductInputProcess}
                            enableSortableRows
                            setOnReorderRows={handleUpdateItemOrder}
                            data={(state.data.item as IPartialProduct).product_inputs_processes || []}
                            columns={columnsProductInputProcess}
                            modeTable="content"
                            noResultsMessage="No hay procesos de producción asignados"
                        />
                    </div>
                }
                {state.data.item_type === "product" &&
                    <div>
                        <span className={`nunito-bold ${StyleModule.subTitle}`}>Descuentos de rangos</span>
                        <GenericTableMemo
                            modelName="Descuentos de rangos"
                            getRowId={getRowIdProductDiscountRange}
                            data={(state.data.item as IPartialProduct).product_discount_ranges || []}
                            columns={columnsProductDiscountRange}
                            modeTable="content"
                            noResultsMessage="No hay descuentos de rangos asignados"
                        />
                    </div>
                }
            </div>
            <div className={StyleModule.containerButtons}>
                <CriticalActionButton
                    label="Cancelar"
                    onClick={onCancel}
                />
                <CriticalActionButton
                    label="Regresar"
                    onClick={handleOnClickBackStep}
                />
                <TertiaryActionButtonCustom
                    label="Guardar y salir"
                    onClick={() => console.log("guardar y salir")}
                    icon={<Bookmark />}
                />
                <MainActionButtonCustom
                    label="Guardar y continuar"
                    onClick={handleOnClickNextStep}
                    icon={<Bookmark />}
                />
            </div>
        </div>
    )
}

export default Step2;