import type {
    ColumnDef
} from "@tanstack/react-table";
import type {
    IInventoryDetails
} from "../../../../../interfaces/inventories";

const columnsInventoryDetails: ColumnDef<IInventoryDetails>[] = [
    {
        accessorKey: "location_id",
        header: "Location ID",
        meta: {
            hidden: true,
            type: "number",
            mode: "single",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "inventory_id",
        header: "Inventory ID",
        meta: {
            hidden: true,
            type: "number",
            mode: "single",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "location_name",
        header: "Location",
        meta: {
            hidden: false,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "item_name",
        header: "Item Name",
        meta: {
            hidden: false,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "item_type",
        header: "Item Type",
        meta: {
            hidden: false,
            type: "enum",
            options: ["product", "input"],
            autoGenerated: false,
        },
    },
    {
        accessorKey: "item_id",
        header: "Item ID",
        meta: {
            hidden: true,
            type: "number",
            mode: "single",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "stock",
        header: "Stock",
        meta: {
            hidden: false,
            type: "number",
            mode: "range",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "committed_qty",
        header: "Committed",
        meta: {
            hidden: false,
            type: "number",
            mode: "range",
            autoGenerated: false,
        },
    },
    // {
    //     accessorKey: "ordered_production_qty",
    //     header: "Planned for Production",
    //     meta: {
    //         hidden: false,
    //         type: "number",
    //         mode: "range",
    //         autoGenerated: false,
    //     },
    // },
    {
        accessorKey: "pending_production_qty",
        header: "Pending Production", 
        meta: {
            hidden: false,
            type: "number",
            mode: "range",
            autoGenerated: false,
        },
    },
    // {
    //     accessorKey: "produced_qty",
    //     header: "Produced", 
    //     meta: {
    //         hidden: false,
    //         type: "number",
    //         mode: "range",
    //         autoGenerated: false,
    //     },
    // },    
    {
        accessorKey: "available",
        header: "Available",
        meta: {
            hidden: false,
            type: "number",
            mode: "range",
            autoGenerated: false,
        },
    },

];

export { columnsInventoryDetails };
