import type { ColumnDef } from "@tanstack/react-table";
import type { IClient } from "../../../../interfaces/clients";
import StyleModule from "./columns.module.css";
import Tag from "../../../../comp/primitives/tag/Tag";

const columnsClients: ColumnDef<IClient>[] = [

    // * VISIBLES
    {
        accessorKey: "company_name",
        header: "Cliente",
        meta: {
            hidden: false,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "email",
        header: "Email",
        meta: {
            hidden: true,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "phone",
        header: "Teléfono",
        meta: {
            hidden: false,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "payment_terms",
        header: "Condiciones de pago",
        meta: {
            hidden: false,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "payment_method",
        header: "Metodo de pago",
        meta: {
            hidden: true,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },
    {
        id: "addresses",
        header: "Dirección",
        accessorFn: (row) => `${row.street}, ${row.street_number}, ${row.neighborhood}, ${row.zip_code}, ${row.city}, ${row.state}, ${row.country}`,
        meta: {
            hidden: false,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "is_active",
        header: "Estado",
        meta: {
            hidden: false,
            type: "boolean",
            booleanLabels: ["Inactivo", "Activo"],
            autoGenerated: false,
        },
        cell: ({ row }) => {
            const isActive = row.original.is_active;
            return (
                <Tag
                    label={isActive ? "Activo" : "Inactivo"}
                    className={isActive ? StyleModule.tagActive : StyleModule.tagInactive}
                />
            );
        },
    },
    // * OCULTOS
    {
        accessorKey: "tax_id",
        header: "Tax ID",
        meta: {
            hidden: true,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "cfdi",
        header: "CFDI",
        meta: {
            hidden: true,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "id",
        header: "ID",
        meta: {
            hidden: true,
            type: "number",
            autoGenerated: true,
        },
    },
    {
        accessorKey: "city",
        header: "City",
        meta: {
            hidden: true,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "state",
        header: "State",
        meta: {
            hidden: true,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "country",
        header: "Country",
        meta: {
            hidden: true,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "zip_code",
        header: "ZIP Code",
        meta: {
            hidden: true,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "credit_limit",
        header: "Credit Limit",
        meta: {
            hidden: true,
            type: "number",
            mode: "range",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "tax_regimen",
        header: "Tax Regimen",
        meta: {
            hidden: true,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "created_at",
        header: "Created At",
        meta: {
            hidden: true,
            type: "date",
            autoGenerated: true,
        },
        enableHiding: false,
    },
    {
        accessorKey: "updated_at",
        header: "Updated At",
        meta: {
            hidden: true,
            type: "date",
            autoGenerated: true,
        },
        enableHiding: false,
    },
];

export default columnsClients;
