import type { ColumnDef } from "@tanstack/react-table";
import type { IProduct } from "../../../interfaces/product";

const columnsProducts: ColumnDef<IProduct>[] = [
    {
        accessorKey: "id",
        header: "ID",
        meta: {
            hidden: true,
            type: "number",
            mode: "range",
            autoGenerated: true,
        },
    },
    {
        accessorKey: "name",
        header: "Name",
        meta: {
            hidden: false,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "type",
        header: "Type",
        meta: {
            hidden: false,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "description",
        header: "Description",
        meta: {
            hidden: false,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "sku",
        header: "SKU",
        meta: {
            hidden: false,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "active",
        header: "Active",
        meta: {
            hidden: false,
            type: "boolean",
            autoGenerated: false,
            booleanLabels: ["Inactive", "Active"],
        },
    },
    {
        accessorKey: "sale_price",
        header: "Sale Price",
        meta: {
            hidden: false,
            type: "number",
            mode: "range",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "photo",
        header: "Photo",
        meta: {
            hidden: true,
            type: "string",
            autoGenerated: false,
        },
        enableHiding: false

    },
    {
        accessorKey: "created_at",
        header: "Created At",
        meta: {
            hidden: true,
            type: "date",
            mode: "range",
            autoGenerated: true,
        },
    },
    {
        accessorKey: "updated_at",
        header: "Updated At",
        meta: {
            hidden: true,
            type: "date",
            mode: "range",
            autoGenerated: true,
        },
    },
];

export { columnsProducts };
