import type {
    ColumnDef
} from "@tanstack/react-table";
import type {
    IInput
} from "../../../../../interfaces/inputs";

const columnsInputs: ColumnDef<IInput>[] = [
    {
        accessorKey: "id",
        header: "ID",
        meta: {
            hidden: true,
            type: "number",
            mode: "range",
            autoGenerated: true,
        },
    },
    {
        accessorKey: "name",
        header: "Name",
        meta: {
            hidden: false,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "input_types_id",
        header: "Input Type",
        meta: {
            hidden: false,
            type: "number",
            mode: "range",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "unit_cost",
        header: "Unit Cost",
        meta: {
            hidden: false,
            type: "number",
            mode: "range",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "supplier",
        header: "Supplier",
        meta: {
            hidden: false,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "photo",
        header: "Photo",
        meta: {
            hidden: true,
            type: "string",
            autoGenerated: false,
        },
        enableHiding: false,
    },
    {
        accessorKey: "status",
        header: "Status",
        meta: {
            hidden: false,
            type: "boolean",
            autoGenerated: false,
            booleanLabels: ["Inactive", "Active"],
        },
    },
    {
        accessorKey: "created_at",
        header: "Created At",
        meta: {
            hidden: true,
            type: "date",
            mode: "range",
            autoGenerated: true,
        },
    },
    {
        accessorKey: "updated_at",
        header: "Updated At",
        meta: {
            hidden: true,
            type: "date",
            mode: "range",
            autoGenerated: true,
        },
    },
];

export { columnsInputs };
