import TertiaryActionButtonCustom from "../../../../../../../comp/primitives/button/custom-button/tertiary-action/TertiaryActionButtonCustom";
import MainActionButtonCustom from "../../../../../../../comp/primitives/button/custom-button/main-action/MainActionButtonCustom";
import CriticalActionButton from "../../../../../../../comp/primitives/button/custom-button/critical-action/CriticalActionButton";
import type { IPartialProductDiscountClient } from "../../../../../../../interfaces/product-discounts-clients";
import { formatCurrency, formatPercentage1_100 } from "../../../../../../../helpers/formttersNumeric";
import GenericTableMemo from "../../../../../../../comp/primitives/table/tableContext/GenericTable";
import ToastMantine from "../../../../../../../comp/external/mantine/toast/base/ToastMantine";
import type { IPartialClientAddress } from "../../../../../../../interfaces/clientAddress";
import type { ClientState, ClientAction } from "../../../../../context/clientTypes"
import type { IPartialClient } from "../../../../../../../interfaces/clients";
import type { RootState } from "../../../../../../../store/store";
import { back_step } from "../../../../../context/clientActions";
import { useCallback, useMemo, type Dispatch } from "react";
import type { ColumnDef } from "@tanstack/react-table";
import { Bookmark, ChevronLeft } from "lucide-react";
import StyleModule from "./Step3.module.css";
import { useSelector } from "react-redux";

interface IStep3 {
    state: ClientState;
    dispatch: Dispatch<ClientAction>;
    onCancel: () => void;
    onCreate: (record: IPartialClient) => Promise<void>;
    onClose: () => void;
}
const Step3 = ({
    state,
    dispatch,
    onCancel,
    onCreate,
    onClose
}: IStep3) => {

    const errorRedux = useSelector((state: RootState) => state.error);

    // * *********** Funciones memoizadas para las tablas ************ 

    const getRowIdAddresses = useMemo(() => (row: IPartialClientAddress, index: number) => row.id?.toString() ?? index.toString(), []);
    const getRowIdDiscounts = useMemo(() => (row: IPartialProductDiscountClient, index: number) => row.id?.toString() ?? index.toString(), []);

    const columnsAddresses: ColumnDef<IPartialClientAddress>[] = useMemo(() => [
        {
            accessorKey: "street",
            header: "Calle",
            meta: {
                hidden: false,
                autoGenerated: true,
                type: "string",
            }
        },
        {
            accessorKey: "street_number",
            header: "Numero",
            meta: {
                hidden: false,
                autoGenerated: true,
                type: "string",
            }
        },
        {
            accessorKey: "neighborhood",
            header: "Colonia",
            meta: {
                hidden: false,
                autoGenerated: true,
                type: "string",
            }
        },
        {
            accessorKey: "city",
            header: "Ciudad",
            meta: {
                hidden: false,
                autoGenerated: true,
                type: "string",
            }
        },
        {
            accessorKey: "state",
            header: "Estado",
            meta: {
                hidden: false,
                autoGenerated: true,
                type: "string",
            }
        },
        {
            accessorKey: "country",
            header: "Pais",
            meta: {
                hidden: false,
                autoGenerated: true,
                type: "string",
            }
        },
        {
            accessorKey: "zip_code",
            header: "CP",
            meta: {
                hidden: false,
                autoGenerated: true,
                type: "string",
            }
        },
    ], []);

    const columnsDiscounts: ColumnDef<IPartialProductDiscountClient>[] = useMemo(() => [
        {
            accessorFn: (row: IPartialProductDiscountClient) => row?.product?.name,
            header: "Producto",
            meta: {
                hidden: false,
                autoGenerated: true,
                type: "string",
            }
        },
        {
            accessorFn: (row: IPartialProductDiscountClient) => row?.product?.sale_price,
            header: "Precio de venta",
            meta: {
                hidden: false,
                autoGenerated: true,
                type: "number",
                mode: "range",
            },
            cell: ({ row }) => formatCurrency(row.original.product?.sale_price ?? 0),
        },
        {
            accessorKey: "discount_percentage",
            header: "Descuento porcentual (%)",
            meta: {
                hidden: false,
                autoGenerated: true,
                type: "number",
                mode: "range",
            },
            cell: ({ row }) => formatPercentage1_100(row.original.discount_percentage ?? 0)
        },
    ], []);

    const handleOnClickBackStep = useCallback(() => {
        dispatch(back_step());
    }, [dispatch]);

    const handleOnClickCreate = useCallback(() => {
        onCreate(state?.data ?? {});
        if (Object.keys(errorRedux).length > 0) {
            Object.entries(errorRedux).forEach(([_, value]) => {
                ToastMantine.error({
                    message: value,
                });
            })
            return;
        }
        onClose();
    }, [onCreate, state.data, errorRedux, ToastMantine, onClose]);

    return (
        <div className={StyleModule.containerStep}>
            <div className={StyleModule.containerContent}>
                <div className={StyleModule.blockInformationContact}>
                    <div className={StyleModule.informationContainer}>
                        <h2 className={StyleModule.subTitle}>Información</h2>
                        <dl className={StyleModule.dl}>
                            <dt className="nunito-bold">Nombre del cliente: </dt>
                            <dd className="nunito-semibold">{state?.data?.company_name}</dd>
                        </dl>
                        <dl className={StyleModule.dl}>
                            <dt className="nunito-bold">Cfdi: </dt>
                            <dd className="nunito-semibold">{state?.data?.cfdi}</dd>
                        </dl>
                    </div>
                    <div className={StyleModule.contactContainer}>
                        <h2 className={StyleModule.subTitle}>Contacto principal</h2>
                        <dl className={StyleModule.dl}>
                            <dt className="nunito-bold">Telefono: </dt>
                            <dd className="nunito-semibold">{state?.data?.phone}</dd>
                        </dl>
                        <dl className={StyleModule.dl}>
                            <dt className="nunito-bold">Correo electrónico: </dt>
                            <dd className="nunito-semibold">{state?.data?.email}</dd>
                        </dl>
                    </div>
                </div>
                <div className={StyleModule.taxAddressContainer}>
                    <h2 className={StyleModule.subTitle}>Dirección y datos comerciales</h2>
                    <div className={StyleModule.addressContainer}>
                        <div className={StyleModule.localAddressContainer}>
                            <dl className={StyleModule.dl}>
                                <dt className="nunito-bold">Calle: </dt>
                                <dd className="nunito-semibold">{state?.data?.street}</dd>
                            </dl>
                            <dl className={StyleModule.dl}>
                                <dt className="nunito-bold">Número: </dt>
                                <dd className="nunito-semibold">{state?.data?.street_number}</dd>
                            </dl>
                            <dl className={StyleModule.dl}>
                                <dt className="nunito-bold">Colonia: </dt>
                                <dd className="nunito-semibold">{state?.data?.neighborhood}</dd>
                            </dl>
                        </div>
                        <div className={StyleModule.mainAddressContainer}>
                            <dl className={StyleModule.dl}>
                                <dt className="nunito-bold">Pais: </dt>
                                <dd className="nunito-semibold">{state?.data?.country}</dd>
                            </dl>
                            <dl className={StyleModule.dl}>
                                <dt className="nunito-bold">Estado: </dt>
                                <dd className="nunito-semibold">{state?.data?.state}</dd>
                            </dl>
                            <dl className={StyleModule.dl}>
                                <dt className="nunito-bold">Ciudad: </dt>
                                <dd className="nunito-semibold">{state?.data?.city}</dd>
                            </dl>
                            <dl className={StyleModule.dl}>
                                <dt className="nunito-bold">Código postal: </dt>
                                <dd className="nunito-semibold">{state?.data?.zip_code}</dd>
                            </dl>
                        </div>
                    </div>
                </div>
                {(state?.data?.addresses?.length ?? 0) > 0 &&
                    <div className={StyleModule.addressesContainer}>
                        <h2 className={StyleModule.subTitle}>Direcciones</h2>

                        <GenericTableMemo
                            modelName="clientAddress"
                            getRowId={getRowIdAddresses}
                            columns={columnsAddresses}
                            data={state.data?.addresses ?? []}
                            noResultsMessage="No hay direcciones asignadas"
                        />
                    </div>
                }
                {(state?.data?.product_discounts_client?.length ?? 0) > 0 &&
                    <div className={StyleModule.discountsContainer}>
                        <h2 className={StyleModule.subTitle}>Descuentos</h2>
                        <GenericTableMemo
                            modelName="clientDiscount"
                            getRowId={getRowIdDiscounts}
                            columns={columnsDiscounts}
                            data={state.data?.product_discounts_client ?? []}
                            noResultsMessage="No hay descuentos asignados"
                        />
                    </div>
                }
            </div>
            <div className={StyleModule.containerButtons}>
                <CriticalActionButton
                    onClick={onCancel}
                    label="Cancelar"
                />
                <TertiaryActionButtonCustom
                    label="Regresar"
                    icon={<ChevronLeft />}
                    onClick={handleOnClickBackStep}
                />
                <MainActionButtonCustom
                    onClick={handleOnClickCreate}
                    label="Guardar y continuar"
                    icon={<Bookmark />}
                />
            </div>
        </div>
    );
};

export default Step3;
