### get
GET http://localhost:3003/logistics/shipping-orders HTTP/1.0

### get
GET http://localhost:3003/logistics/shipping-orders/1 HTTP/1.0

### get
GET http://localhost:3003/logistics/shipping-orders/details/1 HTTP/1.0

### post
POST http://localhost:3003/logistics/shipping-orders HTTP/1.0
Content-Type: application/json

{
  "status": "In Transit",
  "carrier_id": "1",
  "delivery_cost": "50.0000"
}

### PATCH
PATCH http://localhost:3003/logistics/shipping-orders/1 HTTP/1.0
Content-Type: application/json

{
    "name": "Shipping order Diobar"
}

### delete
DELETE http://localhost:3003/logistics/shipping-orders/132


###
POST http://localhost:3003/logistics/shipping-orders/complete
Content-Type: application/json

{
  "name": "ORDER12345",
  "status": "released",
  "carrier_id": 1,
  "load_evidence": null,
  "delivery_cost": 100.5,
  "products": [
    { "purchase_order_product_id": 1 }
  ]
}
