import TertiaryActionButtonCustom from "../../../../../../../comp/primitives/button/custom-button/tertiary-action/TertiaryActionButtonCustom";
import SingleImageLoaderCustom from "../../../../../../../comp/primitives/image-loader/single/custom/SingleImageLoaderCustom";
import type { IPartialProductDiscountRange } from "../../../../../../../interfaces/product-discounts-ranges";
import type { IPartialProductInputProcess } from "../../../../../../../interfaces/productInpustProcesses";
import GenericTableMemo from "../../../../../../../comp/primitives/table/tableContext/GenericTable";
import type { IPartialProductProcess } from "../../../../../../../interfaces/productsProcesses";
import { formatCurrency, formatNumber } from "../../../../../../../helpers/formttersNumeric"
import type { IPartialProductInput } from "../../../../../../../interfaces/productsInputs";
import base64ToFileOrNull from "../../.../../../../../../../scripts/convertBase64ToFile";
import type { IPartialProduct } from "../../../../../../../interfaces/product";
import type { ItemAction, ItemState } from "../../../../../context/itemTypes";
import type { IPartialInput } from "../../../../../../../interfaces/inputs";
import { useCallback, useMemo, useState, type Dispatch } from "react";
import { set_draft_item, set_step } from "../../../../../context/itemActions";
import type { ColumnDef } from "@tanstack/react-table";
import StyleModule from "./Step3.module.css"
import { ChevronLeft, Pencil } from "lucide-react";

interface Step3Props {
    state: ItemState,
    dispatch: Dispatch<ItemAction>,
    onClose: () => void
}

const Step3 = ({ state, dispatch, onClose }: Step3Props) => {

    const computePhotoFiles = useCallback((): File | null => {
        if (!state.data.item) return null;
        return base64ToFileOrNull(state.data.item?.photo || null, "photo")
    }, [state.data.item]);

    // console.log('photo ', computePhotoFiles());

    const [photo, setPhoto] = useState<File | null>(computePhotoFiles());

    //  * ************ Components Table ProductInput ************ 

    const getRowIdProductInput = useMemo(() => (row: IPartialProductInput, index: number) => row.inputs?.id && row.inputs.id?.toString() || index.toString(), []);

    const columnsProductInput: ColumnDef<IPartialProductInput>[] = useMemo(() => [
        {
            id: "custom_id",
            header: "Id",
            accessorFn: (row: IPartialProductInput) => row.inputs?.custom_id,
            meta: {
                hidden: false,
                type: "number",
                mode: "range",
                autoGenerated: false,
            },
        },
        {
            id: "name",
            header: "Insumo",
            accessorFn: (row: IPartialProductInput) => row.inputs?.name,
            meta: {
                hidden: false,
                type: "string",
                typeText: "text",
                autoGenerated: false,
            },
        },
    ], []);

    //  * ************ Components Table ProductProcess ************ 

    const getRowIdProductProcess = useMemo(() => (row: IPartialProductProcess, index: number) => (row?.id?.toString()) || index.toString(), []);

    const columnsProductProcess: ColumnDef<IPartialProductProcess>[] = useMemo(() => [
        {
            id: "name",
            header: "Nombre",
            accessorFn: (row: IPartialProductProcess) => row.process?.name,
            meta: {
                hidden: false,
                type: "string",
                typeText: "text",
                autoGenerated: false,
            },
        },
        {
            id: "sort_order",
            header: "Orden",
            accessorFn: (row: IPartialProductProcess) => row.sort_order,
            meta: {
                hidden: false,
                type: "number",
                mode: "range",
                autoGenerated: false,
            },
        },
        {
            id: "inputs",
            header: "Insumos",
            accessorFn: (row: IPartialProductProcess) => row.product_input_process,
            meta: {
                hidden: false,
                type: "number",
                mode: "range",
                autoGenerated: false,
            },
            cell: ({ row }) => {
                const value = row.original.product_input_process;
                return (
                    <div className={StyleModule.containerInputs}>
                        {
                            value?.map((input: IPartialProductInputProcess, index: number) => {
                                return (
                                    <div key={input.id} className={StyleModule.inputRowCell}>
                                        <span>{`${index + 1}. ${input.product_input?.inputs?.name}`}</span>
                                        <span>{`Cantidad: ${Number(input.qty)}`}</span>
                                    </div>
                                )
                            })
                        }
                    </div>
                )
            }
        }
    ], []);

    //  * ************ Components Table ProductDiscountRange ************ 

    const getRowIdProductDiscountRange = useMemo(() => (row: IPartialProductDiscountRange, index: number) => (row?.id && row?.id.toString()) || index.toString(), []);

    const columnsProductDiscountRange: ColumnDef<IPartialProductDiscountRange>[] = useMemo(() => [
        {
            accessorKey: "min_qty",
            header: "Mínimo de piezas",
            meta: {
                hidden: false,
                type: "number",
                mode: "range",
                autoGenerated: false,
            },
            cell: ({ row }) => formatNumber(Number(row.original.min_qty))
        },
        {
            accessorKey: "max_qty",
            header: "Máximo de piezas",
            meta: {
                hidden: false,
                type: "number",
                mode: "range",
                autoGenerated: false,
            },
            cell: ({ row }) => formatNumber(Number(row.original.max_qty))
        },
        {
            accessorKey: "unit_price",
            header: "Precio",
            meta: {
                hidden: false,
                type: "number",
                mode: "range",
                autoGenerated: false,
            },
            cell: ({ row }) => formatCurrency(Number(row.original.unit_price))
        },
    ], []);

    // * ************ Handlers ************ 

    const handleOnClickEdit = useCallback(() => {
        dispatch(set_draft_item(state.data));
        dispatch(set_step(0));
    }, [dispatch, state.data]);

    const handleOnClickBackStep = useCallback(() => onClose(), [onClose]);

    return (
        <div className={StyleModule.containerStep}>
            <div className={StyleModule.containerContent}>
                <div className={StyleModule.firstBlock}>
                    {state.data.item?.photo &&
                        <div className={StyleModule.imageContainer}>
                            <SingleImageLoaderCustom
                                value={photo}
                                onChange={setPhoto}
                                isEditable={false}
                            />
                        </div>
                    }
                    <div className={StyleModule.infoContainer}>
                        <div>
                            <h2 className="nunito-bold">Información del producto</h2>
                            <dl className={`nunito-bold ${StyleModule.definitionList}`}>
                                <dt>Nombre del producto: </dt>
                                <dd>{state.data.item?.name}</dd>
                            </dl>
                            <dl className={`nunito-bold ${StyleModule.definitionList}`}>
                                <dt>ID único: </dt>
                                <dd>{state.data.item?.custom_id}</dd>
                            </dl>
                            <dl className={`nunito-bold ${StyleModule.definitionList}`}>
                                <dt>Categoría: </dt>
                                <dd>
                                    {
                                        state.data.item_type === "product"
                                            ? "Producto terminado"
                                            : "Materia prima"
                                    }
                                </dd>
                            </dl>
                            <dl className={`nunito-bold ${StyleModule.definitionList}`}>
                                <dt>Código de barras: </dt>
                                <dd>{state.data.item?.barcode}</dd>
                            </dl>
                            {state.data.item?.description &&
                                <div className={`nunito-bold ${StyleModule.definitionListDiv}`}>
                                    <span>Descripción:</span> {state.data.item?.description}
                                </div>
                            }
                        </div>
                        <div>
                            <h2 className="nunito-bold">Características e información adicional</h2>
                            {state.data.item?.presentation &&
                                <dl className={`nunito-bold ${StyleModule.definitionList}`}>
                                    <dt>Presentación: </dt>
                                    <dd>{state.data.item?.presentation}</dd>
                                </dl>
                            }
                            {state.data.item?.storage_conditions &&
                                <dl className={`nunito-bold ${StyleModule.definitionList}`}>
                                    <dt>Condiciones de almacenamiento: </dt>
                                    <dd>{state.data.item.storage_conditions}</dd>
                                </dl>
                            }
                            {state.data.item_type === "product" &&
                                <dl className={`nunito-bold ${StyleModule.definitionList}`}>
                                    <dt>Costo de producción: </dt>
                                    <dd>{formatCurrency(((state.data.item) as IPartialProduct).production_cost as number)}</dd>
                                </dl>
                            }
                            <dl className={`nunito-bold ${StyleModule.definitionList}`}>
                                <dt>
                                    {
                                        state.data.item_type === "product"
                                            ? "Precio de venta: "
                                            : "Precio de compra: "
                                    }
                                </dt>
                                <dd>
                                    {
                                        state.data.item_type === "product"
                                            ? formatCurrency((state.data.item as IPartialProduct).sale_price as number)
                                            : formatCurrency((state.data.item as IPartialInput).unit_cost as number)
                                    }
                                </dd>
                            </dl>
                        </div>
                    </div>
                </div>
                {(state.data.item_type === "product" && (((state.data.item as IPartialProduct).products_inputs ?? []).length > 0)) &&
                    <div className={StyleModule.externalContainerTable}>
                        <div className={StyleModule.contentHeaderTable}>
                            <span className={`nunito-bold ${StyleModule.subTitle}`}>Insumos de producción</span>
                        </div>
                        <GenericTableMemo
                            modelName="Insumos de producción"
                            getRowId={getRowIdProductInput}
                            data={(state.data.item as IPartialProduct).products_inputs || []}
                            columns={columnsProductInput}
                            modeTable="content"
                            noResultsMessage="No hay insumos de producción asignados"
                        />
                    </div>
                }
                {(state.data.item_type === "product" && (((state.data.item as IPartialProduct).product_processes ?? []).length > 0)) &&
                    <div className={StyleModule.externalContainerTable}>
                        <div className={StyleModule.contentHeaderTable}>
                            <span className={`nunito-bold ${StyleModule.subTitle}`}>Procesos de producción</span>
                        </div>
                        <GenericTableMemo
                            modelName="Procesos de producción"
                            getRowId={getRowIdProductProcess}
                            data={(state.data.item as IPartialProduct).product_processes || []}
                            columns={columnsProductProcess}
                            modeTable="content"
                            noResultsMessage="No hay procesos de producción asignados"
                        />
                    </div>
                }
                {(state.data.item_type === "product" && (((state.data.item as IPartialProduct).product_discount_ranges ?? []).length > 0)) &&
                    <div className={StyleModule.externalContainerTable}>
                        <div className={StyleModule.contentHeaderTable}>
                            <span className={`nunito-bold ${StyleModule.subTitle}`}>Descuentos de rangos</span>
                        </div>
                        <GenericTableMemo
                            modelName="Descuentos de rangos"
                            getRowId={getRowIdProductDiscountRange}
                            data={(state.data.item as IPartialProduct).product_discount_ranges || []}
                            columns={columnsProductDiscountRange}
                            modeTable="content"
                            noResultsMessage="No hay descuentos de rangos asignados"
                        />
                    </div>
                }
            </div>
            <div className={StyleModule.containerButtons}>
                <TertiaryActionButtonCustom
                    label="Regresar"
                    onClick={handleOnClickBackStep}
                    icon={<ChevronLeft />}
                />
                <TertiaryActionButtonCustom
                    label="Editar"
                    onClick={handleOnClickEdit}
                    icon={<Pencil />}
                />
            </div>
        </div >
    )
}

export default Step3;