import type { ColumnDef } from "@tanstack/react-table";
import type { IPurchasedOrder } from "./../../../interfaces/purchasedOrder";

const columnsPurchasedOrders: ColumnDef<IPurchasedOrder>[] = [
  {
    accessorKey: "id",
    header: "ID",
    meta: {
      hidden: false,
      type: "number",
      mode: "range",
      autoGenerated: true,
    },
  },
  {
    accessorKey: "order_code",
    header: "Order Code",
    meta: {
      hidden: false,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "delivery_date",
    header: "Delivery Date",
    meta: {
      hidden: false,
      type: "date",
      mode: "single",
      autoGenerated: false,
    },
  },
  {
    accessorKey: "status",
    header: "Status",
    meta: {
      hidden: false,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "client_id",
    header: "Client ID",
    meta: {
      hidden: true,
      type: "number",
      mode: "single",
      autoGenerated: false,
    },
  },
  {
    accessorKey: "company_name",
    header: "Company Name",
    meta: {
      hidden: false,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "tax_id",
    header: "Tax ID",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "email",
    header: "Email",
    meta: {
      hidden: false,
      type: "string",
      autoGenerated: false,
      typeText: "email",
    },
  },
  {
    accessorKey: "phone",
    header: "Phone",
    meta: {
      hidden: false,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "city",
    header: "City",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "state",
    header: "State",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "country",
    header: "Country",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "address",
    header: "Address",
    meta: {
      hidden: false,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "payment_terms",
    header: "Payment Terms",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "zip_code",
    header: "ZIP Code",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "tax_regimen",
    header: "Tax Regimen",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "cfdi",
    header: "CFDI",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "payment_method",
    header: "Payment Method",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "client_address_id",
    header: "Client Address ID",
    meta: {
      hidden: true,
      type: "number",
      mode: "single",
      autoGenerated: false,
    },
  },
  {
    accessorKey: "shipping_address",
    header: "Shipping Address",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "shipping_city",
    header: "Shipping City",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "shipping_state",
    header: "Shipping State",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "shipping_country",
    header: "Shipping Country",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "shipping_zip_code",
    header: "Shipping ZIP Code",
    meta: {
      hidden: true,
      type: "string",
      autoGenerated: false,
      typeText: "text",
    },
  },
  {
    accessorKey: "total_price",
    header: "Total Price",
    meta: {
      hidden: true,
      type: "number",
      mode: "range",
      autoGenerated: false,
    },
  },
  {
    accessorKey: "created_at",
    header: "Created At",
    meta: {
      hidden: true,
      type: "date",
      mode: "single",
      autoGenerated: true,
    },
  },
  {
    accessorKey: "updated_at",
    header: "Updated At",
    meta: {
      hidden: true,
      type: "date",
      mode: "single",
      autoGenerated: true,
    },
  },
];

export { columnsPurchasedOrders };
