import type {
    ColumnDef
} from "@tanstack/react-table";
import type {
    IProductionOrder
} from "../../../../../interfaces/productionOrder";
import stylesModules from "./columns.module.css";

const columnsProductionOrders: ColumnDef<IProductionOrder>[] = [

    {
        accessorKey: "product_name",
        header: "Product Name",
        meta: {
            hidden: false,
            type: "string",
            typeText: "text",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "qty",
        header: "Quantity",
        meta: {
            hidden: false,
            type: "number",
            mode: "range",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "status",
        header: "Estado",
        meta: {
            hidden: false,
            type: "string",
            autoGenerated: false,
            typeText: "text",
        },
        cell: ({ getValue }) => {
            const status = getValue() as string;
            return (
                <span
                    className={'nunito-semibold ' +
                        `${stylesModules.tag} ${stylesModules[status.toLowerCase()]}`
                    }>{status}
                </span>
            );
        },
    },
    // ! COLUMNAS OCULTAS ************************************************** */
    {
        accessorKey: "id",
        header: "ID",
        meta: {
            hidden: true,
            type: "number",
            mode: "range",
            autoGenerated: true,
        },
    },
    {
        accessorKey: "order_id",
        header: "Order ID",
        meta: {
            hidden: true,
            type: "number",
            mode: "single",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "product_id",
        header: "Product ID",
        meta: {
            hidden: true,
            type: "number",
            mode: "single",
            autoGenerated: false,
        },
    },
    {
        accessorKey: "order_type",
        header: "Order Type",
        meta: {
            hidden: true,
            type: "enum",
            autoGenerated: false,
            options: ["internal", "client"],
        },
    },
    {
        accessorKey: "created_at",
        header: "Created At",
        meta: {
            hidden: true,
            type: "date",
            mode: "single",
            autoGenerated: true,
        },
    },
    {
        accessorKey: "updated_at",
        header: "Updated At",
        meta: {
            hidden: true,
            type: "date",
            mode: "single",
            autoGenerated: true,
        },
    },
];

export { columnsProductionOrders };
