import type {
    ColumnDef,
    Row
} from "@tanstack/react-table";
import type {
    IProductionOrder
} from "../../../../../interfaces/productionOrder";
import stylesModules from "./columns.module.css";
import SingleProgressBarMantine from "../../../../../comp/external/mantine/progress-bar/single-progress-bar/SingleProgressBarMantine";

interface IColumnsProductionOrdersProps {
    onClickContent: (e: React.MouseEvent, row: Row<IProductionOrder>) => void;
}


const columnsProductionOrders = ({
    onClickContent,
}: IColumnsProductionOrdersProps): ColumnDef<IProductionOrder>[] => [
        {
            accessorKey: "id",
            header: "Order ID",
            meta: {
                hidden: false,
                type: "number",
                mode: "range",
                autoGenerated: true,
            },
        },
        {
            accessorKey: "product_name",
            header: "Producto",
            meta: {
                hidden: false,
                type: "string",
                typeText: "text",
                autoGenerated: false,
            },
        },
        {
            id: "planta",
            header: "Planta",
            accessorFn: (row) => row.extra_data?.location.name,
            cell: ({ row }) => {
                const locationName = row.original.extra_data?.location.name;
                return <div
                    className={stylesModules.containerTextDecoration}
                    onClick={(e) => onClickContent(e, row)}
                >
                    {locationName}
                </div>;
            },
            meta: {
                hidden: false,
                type: "string",
                typeText: "text",
                autoGenerated: false,
            },
        }, {
            id: "lineaProduccion",
            header: "Linea de produccion",
            accessorFn: (row) => row.extra_data?.production_line.name,
            cell: ({ row }) => {
                const productionLineName = row.original.extra_data?.production_line.name;
                const isActive = row.original.extra_data?.production_line.is_active;
                return (
                    <div
                        className={
                            `${stylesModules.containerTextDecoration} ` +
                            `${isActive
                                ? stylesModules.containerProductionLine
                                : stylesModules.containerProductionLineInactive}
                            `
                        }
                        onClick={(e) => onClickContent(e, row)}
                    >
                        {productionLineName}
                    </div>
                );
            },
            meta: {
                hidden: false,
                type: "string",
                typeText: "text",
                autoGenerated: false,
            },
        },
        {
            accessorFn: (row) => row.extra_data?.production_qty,
            header: "Progreso",
            cell: ({ row }) => {
                const productionBreakdown = row.original.production_breakdown;
                const allStages = productionBreakdown?.all_stages;
                // Encuentra el objeto con el valor más alto
                const maxItem = allStages?.reduce((prev, current) =>
                    (current?.stage || 0) > (prev?.stage || 0) ? current : prev
                );

                return (
                    <div className={stylesModules.containerProgressQtyProduction}>
                        <SingleProgressBarMantine
                            value={Number(maxItem?.done_at_stage)}
                            total={Number(productionBreakdown?.order_qty)}
                            classNameLabel={stylesModules.labelProgressBarTable}
                            classNameRoot={stylesModules.rootProgressBarTable}
                            classNameSection={stylesModules.sectionProgressBarTable}
                        />
                    </div>
                );
            }

        },
        {
            accessorFn: (row) => row.extra_data?.scrap_qty,
            header: "Scrap",
            cell: ({ row }) => {
                const scrapQty = row.original.extra_data?.scrap_qty;
                return <div>
                    {scrapQty}
                </div>;
            }
        },
        {
            accessorKey: "status",
            header: "Estado",
            meta: {
                hidden: false,
                type: "string",
                autoGenerated: false,
                typeText: "text",
            },
            cell: ({ getValue }) => {
                const status = getValue() as string;
                return (
                    <span
                        className={'nunito-semibold ' +
                            `${stylesModules.tag} ${stylesModules[status.toLowerCase()]}`
                        }>{status}
                    </span>
                );
            },
        },
        // ! COLUMNAS OCULTAS ************************************************** */
        {
            accessorKey: "qty",
            header: "Quantity",
            meta: {
                hidden: true,
                type: "number",
                mode: "range",
                autoGenerated: false,
            },
        },
        {
            accessorKey: "order_id",
            header: "Order ID",
            meta: {
                hidden: true,
                type: "number",
                mode: "single",
                autoGenerated: false,
            },
        },
        {
            accessorKey: "product_id",
            header: "Product ID",
            meta: {
                hidden: true,
                type: "number",
                mode: "single",
                autoGenerated: false,
            },
        },
        {
            accessorKey: "order_type",
            header: "Order Type",
            meta: {
                hidden: true,
                type: "enum",
                autoGenerated: false,
                options: ["internal", "client"],
            },
        },
        {
            accessorKey: "created_at",
            header: "Created At",
            meta: {
                hidden: true,
                type: "date",
                mode: "single",
                autoGenerated: true,
            },
        },
        {
            accessorKey: "updated_at",
            header: "Updated At",
            meta: {
                hidden: true,
                type: "date",
                mode: "single",
                autoGenerated: true,
            },
        },
    ];

export { columnsProductionOrders };
